import groovy.sql.Sql

/**
 * @author aakash on 13/9/17.
 */

//@Grab('org.hsqldb:hsqldb:2.3.2')
//@GrabConfig(systemClassLoader=true)

def url = 'jdbc:hsqldb:mem:myDB'
def user = 'sa'
def password = ''
def driver = 'org.hsqldb.jdbcDriver'
def sql = Sql.newInstance(url, user, password, driver)

sql.execute '''
  CREATE TABLE Author (
    id          INTEGER GENERATED BY DEFAULT AS IDENTITY,
    firstname   VARCHAR(64),
    lastname    VARCHAR(64)
  );
'''
sql.execute "INSERT INTO Author (firstname, lastname) VALUES ('Jessica', 'Jones')"
sql.execute "INSERT INTO Author (firstname, lastname) VALUES ('Luke', 'Cage')"
sql.execute "INSERT INTO Author (firstname, lastname) VALUES ('Matt', 'Murdock')"

sql.eachRow('SELECT firstname, lastname FROM Author'){ row ->
    println row
}
